export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_MENU = 'USER_MENU'
export const USER_DEFAULT_MENU = 'USER_DEFAULT_MENU'

export const GET_LATEST_MARK_CHANGE = 'GET_LATEST_MARK_CHANGES'
export const GET_ALL_MARK_CHANGE = 'GET_ALL_MARK_CHANGES'

export const LATEST_MESSAGE_BOARD = 'LATEST_MESSAGE_BOARD'

export const HOME_CAROUSEL = 'HOME_CAROUSEL'
